[package]
name = "rust_synth_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.3"
optargs = "0.1.2"
rand = "0.8.5"
rhai = "1.15.1"
sdl2 = {version="0.35.2", features = ["bundled"]}
